# Generated by Django 3.0.1 on 2019-12-29 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='data',
        ),
        migrations.RemoveField(
            model_name='match',
            name='state',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synchronize.Match'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synchronize.Match'),
        ),
        migrations.AlterField(
            model_name='action',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synchronize.Match'),
        ),
        migrations.AlterField(
            model_name='score',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synchronize.Match'),
        ),
    ]
