# Generated by Django 3.0.1 on 2019-12-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synchronize', '0003_auto_20191230_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='synchronize.Match'),
        ),
    ]
